<body>
<?php if(isset($_layoutParams2['js']) && count($_layoutParams2['js']))
    for($i=0;$i<count($_layoutParams2['js']);$i++)
        echo      "<script src='". $_layoutParams2['js'][$i]."'></script>";
?>

<div class="full-box login-container cover">
	<form action="" method="POST" autocomplete="off" class="logInForm">
		<p class="text-center text-muted"><i class="zmdi zmdi-account-circle zmdi-hc-5x"></i></p>
		<p class="text-center text-muted text-uppercase">Inicia sesión con tu cuenta</p>
		<div class="form-group label-floating">
		  <label class="control-label" for="UserName">Usuario</label>
		  <input required="" class="form-control" id="carnet" name="carnet" type="text" style="color: #FFF;">
		  <p class="help-block">Escribe tú nombre de usuario</p>
		</div>
		<div class="form-group label-floating">
		  <label class="control-label" for="UserPass">Contraseña</label>
		  <input required="" class="form-control" id="password" name="password" type="password" style="color: #FFF;">
		  <p class="help-block">Escribe tú contraseña</p>
		</div>
		<div class="form-group text-center">
			<input type="submit" value="Iniciar sesión" class="btn btn-info" style="color: #FFF;">
		</div>
    <div class="form-group text-center">
    <p>
		<a href="<?php echo BASE_URL."index/crearcuenta/"?>">
			<h4>Crear cuenta</h4>
			<!--<input type="" id="crear" value="Crear Cuenta" class="btn btn-info" style="color: #FFF;" >-->
			</a>
		</div>
	</form>
</div>

<div id="crear" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
	<div class="modal-contenido">
		<a href="#">X</a>
		<h2>Crea tu cuenta</h2>
		
	</div>
</div>
</body>