<!-- Modal -->
<div id="NuevaAsignatura" class="modal fade" role="dialog" style="z-index: 100000">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Nueva Asignatura</h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body">
                <p class="statusMsg"></p>
                 <form id="form_nueva_asig" action="" method="post" name="formasig">
                  <input type="hidden" value="1" name="newAsignatura" />
                    <div class="form-group">
                        <label for="inputid">Codigo de la Asignatura</label>
                        <input type="text" class="form-control" id="inputId" name="inputId"  placeholder="ingrese codigo"/>
                    </div>
                    <div class="form-group">
                        <label for="inputnombre">Nombre</label>
                        <input type="text" class="form-control" id="inputNombre" name="inputNombre" placeholder="ingrese el nombre"/>
                    </div>
                    <div class="form-group">
                        <label for="inputcredito">Creditos</label>
                        <input type="number" class="form-control" id="inputCredito" name="inputCredito" value="1" />
                    </div>
             <button type="submit" class="btn btn-primary" id="creacion_asig">Crear</button>
                </form>
            </div>
            
            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
               
            </div>
        </div>
    </div>

</div>