 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";?> 
  
<section id="contenido">
 <div id="url"> <input type="hidden" value="<?=BASE_URL?>" id="base_url" /></div> 
    <section class="wrapper"> 
<div class="row content-panel">
    
        <h1 class="text-center">Asignaturas</h1>
 <div class="top-menu">
       <ul class="nav pull-left top-menu">
         <li><a class="logout" data-toggle="modal" href="#" data-target="#NuevaAsignatura">Nueva </a></li>
      </ul>
  </div>
  <div class="col-lg-12">  
<div class="container"> 
<!-- TABLA DE LAS Asignatura -->
<table class="table  datatable">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre de la Asignatura</th>
      <th scope="col">Creditos</th>
      <th scope="col">Accion</th>
    
      
    </tr>
  </thead>
  <tbody>
    <tr>
    <?php 
        foreach($this->Get_Asignaturas  as $asignatura){   
    ?>
      <td scope="row"> <?=$asignatura['id_Asignatura']?> </td>
      <td> <?=$asignatura['nombre']?> </td>
      <td> <?=$asignatura['credito']?> </td>
      <td><button class="btn btn-info editBoton" >Editar</button>
      / <button class="btn-borrar_asig btn btn-danger">Borrar</button> </td>
    </tr>
    
        <?php }?>

  </tbody>
</table>
<script type="text/javascript">
  $(document).ready(function(){
    $(".datatable").DataTable();
  })
</script>
<!-- FIN DE LA TABLA -->
</div><!-- FIN DEl dDIV CONTAINER-->
 </div>
</div>
    </section>
</section>






<!-- Modal -->
<div id="NuevaAsignatura" class="modal fade" role="dialog" style="z-index: 100000">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">
                    <span aria-hidden="true">×</span>
                    <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Nueva Asignatura</h4>
            </div>
            
            <!-- Modal Body -->
            <div class="modal-body">
                <p class="statusMsg"></p>
                 <form id="form_nueva_asig" action="" method="post" name="formasig">
                  <input type="hidden" value="1" name="newAsignatura"/>
                    <div class="form-group">
                        <label for="inputid">Codigo de la Asignatura</label>
                        <input type="text" class="form-control" id="inputId" name="inputId"  placeholder="ingrese codigo"  required />
                    </div>
                    <div class="form-group">
                        <label for="inputnombre">Nombre</label>
                     <input type="text" class="form-control" id="inputNombre" name="inputNombre" placeholder="ingrese el nombre" required />
                    </div>
                    <div class="form-group">
                        <label for="inputcredito">Creditos</label>
                        <input type="number" class="form-control" id="inputCredito" name="inputCredito" value="1" required />
                    </div>
             <button type="submit" class="btn btn-primary" id="creacion_asig">Crear</button>

             
                </form>
                 
            </div>

            
            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
               
            </div>
        </div>
    </div>

</div>