<section id="contenido">
    <section class="wrapper"> 
<div class="row content-panel">
    <div class="col-lg-12">

    <h3>Hola Profesor, Crea tú clase</h3>
 <form id="form_CrearClase" action="" method="post" name="formclass">
   <input type="hidden" value="1" name="crear_clase" />
  <div class="form-row">
    
     <div class="form-group col-md-6">
      <label for="idclass">Codigo de clase</label>
      <input type="text" class="form-control" id="id_clase" name="id_clase" placeholder="Código de Clase">
    </div>
    <div class="form-group col-md-6">
      <label for="tema">Nombre</label>
      <input type="text" class="form-control" id="nombre_clase" name="nombre_clase" placeholder="Nombre de la Clase">
    </div>
   
     <div class="form-group col-md-6">
      <label for="Asignatura">Asignatura</label>
      <select name="clase_asignatura" id="clase_asignatura" class="form-control">
        <option value="0">Seleccione la Asignatura</option>
        <?php 
          foreach($this->Get_Asignaturas as $Asignatura){
          ?>
          <option value="<?=$Asignatura['id_Asignatura']?>"><?=$Asignatura['nombre']?></option>
        <?php } ?>
      </select>
    </div>
    <div class="form-group col-md-6">
    <label for="fecha_clase">Fecha de Creación</label>
    <input type="date" class="form-control" id="fecha_clase" name="fecha_clase">
  </div>
    <div class="form-group">
      <label for="contenido_clase">Contenido</label>
      <textarea  id="contenido_clase" name="contenido_clase" class="form-control" cols="30" rows="10" placeholder="Contenido de la clase" form="form_CrearClase"></textarea>
   
    </div>
  </div>
  
  
  <button type="submit" class="btn btn-primary" id="creacion_clase">Crear</button>
</form>

    </div>
</div>
    </section>
</section>


