<div class="container">
<input type="hidden" name="generarCodigoC" value="1">
<button class="btn btn-danger" type="submit" name="generarC" >Generar Código</button>
</div>
<div class="container">

<br>
<form id="formularioclase" action="" method="POST">
<input type="hidden" name="enviarClase" value="1" /> 

  <fieldset>
  <legend>Crear Clase</legend>
  <div class="form-group" >

  <label for="idoculto"><?php 'profesor/generarCodigo/';?></label>

  <label for="identificador" class="control-label col-md-2">Escriba un Identificador para la clase <em>*</em></label>
  <div class="col-md-10">
  <input type="text" name="id" id="identificador" class="form-control"><br>
  </div>
  </div>
  <div class="form-group">
    <label class="control-label col-md-2" for="nom">Asignatura de la clase <em>*</em></label>
    <div class="col-md-10">
      <input id="nom" name="nombre" class="form-control"><br>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-md-2" for="tem">Tema de la clse</label>
    <div class="col-md-10">
      <input id="tem" name="tema" placeholder="" class="form-control"><br>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label col-md-2" for="conten">Contenido de la clse</label>
    <div class="col-md-10">
      <input id="conten" name="contenido" placeholder="" class="form-control"><br>
    </div>
  </div>

  <div class="form-group">
    <label class="" for="image">Imagen <em>*</em></label>
    <div class="">
      <input name="imagen" type="file" src="" alt="" placeholder="Agregar Imagen" id="image"><br>
    </div>
  </div>

  <div class="form-group">
    <label class="" for="vid">Agegue un video <em>*</em></label>
    <div class="">
      <input type="file" name="video" id="vid" placeholder="Seleccione un archivo"><br>
    </div>
  </div>

  <div class="form-group">
    <label class="control-label" for="date">Seleccione la Fecha de Inicio <em>*</em></label>
    <div class="">
      <input type="date" id="date" name="fecha" placeholder=""><br>
    </div>
    <input type="hidden" name="enviarClase" value="1" />
  </div>
</fieldset>
<button class="btn btn-primary" type="submit" id="guardar_clase"> <span class ="fa fa-check" aria-hidden="true"></span> GUARDAR </button>

</form>
</div>
