<section id="contenido">
    <section class="wrapper"> 
<div class="row content-panel">
    <div class="col-lg-12">

    <h3>Hola Profesor, Crea tú clase</h3>
 <form>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="tema">Nombre</label>
      <input type="text" class="form-control" id="nombre_clase" placeholder="Nombre de la Clase">
    </div>
    <div class="form-group col-md-6">
    <label for="fecha_clase">Fecha de Creación</label>
    <input type="date" class="form-control" id="fecha">
  </div>
    <div class="form-group">
      <label for="contenido_clase">Contenido</label>
      <textarea name="" id="contenido_clase" class="form-control" cols="30" rows="10" placeholder="Contenido de la clase"></textarea>
   
    </div>
  </div>
  
  <div class="form-group col-md-6">
    <label for="inputAddress">Address</label>
    <input type="text" class="form-control" id="inputAddress" placeholder="1234 Main St">
  </div>

  <div class="form-group">
    <label for="inputAddress2">Address 2</label>
    <input type="text" class="form-control" id="inputAddress2" placeholder="Apartment, studio, or floor">
  </div>
  <div class="form-row">
    <div class="form-group col-md-6">
      <label for="inputCity">City</label>
      <input type="text" class="form-control" id="inputCity">
    </div>
    <div class="form-group col-md-4">
      <label for="inputState">State</label>
      <select id="inputState" class="form-control">
        <option selected>Choose...</option>
        <option>...</option>
      </select>
    </div>
    <div class="form-group col-md-2">
      <label for="inputZip">Zip</label>
      <input type="text" class="form-control" id="inputZip">
    </div>
  </div>
  <div class="form-group">
    <div class="form-check">
      <input class="form-check-input" type="checkbox" id="gridCheck">
      <label class="form-check-label" for="gridCheck">
        Check me out
      </label>
    </div>
  </div>
  <button type="submit" class="btn btn-primary">Sign in</button>
</form>

    </div>
</div>
    </section>
</section>


