 <!-- ***********************************************************************************************************************************
        Contenido de la vista profesor
 *********************************************************************************************************************************************************** -->
 <!--main content start-->
 <section id="main-content">
   <section class="wrapper">
     <div class="row">
       <div class="col-lg-9 main-chart">
         <!--CUSTOM CHART START -->
         <div class="border-head">
           <h3>Vista del profesor</h3>
         </div>
         <ul class="nav nav-tabs" id="myTab" role="tablist">
           <li class="nav-item" role="presentation">
             <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Clases</a>
           </li>
           <li class="nav-item" role="presentation">
             <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Partcipantes</a>
           </li>
           <li class="nav-item" role="presentation">
             <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Informenes</a>
           </li>
         </ul>
         <div class="tab-content" id="myTabContent">
           <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">.
            <div class="border-head">
              <h3>Home</h3>
            </div> ..
            </div>
           <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
           <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
         </div>
         <!-- /col-lg-3 -->
       </div>

     </div>
     </div>
     <!-- /row -->
   </section>
 </section>
 <!--main content end-->