 <!-- ***********************************************************************************************************************************
        Contenido de la vista profesor
 *********************************************************************************************************************************************************** -->
 <!--main content start-->
 <?php if(isset($_layoutParams['js']) && count($_layoutParams['js']))
    for($i=0;$i<count($_layoutParams['js']);$i++)
        echo "<script src='". $_layoutParams['js'][$i]."'></script>";?> 
  
 <section id="contenido">
    <section class="wrapper">
        <div class="row">
          <div class="col-xs-12 col-md-12 ">        

        
    <ul class="nav nav-tabs nav-justified sidebar-menu" role="tablist">
    <li role="presentation" class="active">
        <a href="#id-of-content-1" role="tab" data-toggle="tab">
            Clases
        </a>
    </li>
    <li role="presentation" >
        <a href="#id-of-content-2" role="tab" data-toggle="tab">
            Participantes
        </a>
    </li>
    <li role="presentation">
        <a href="#id-of-content-3" role="tab" data-toggle="tab">
            Informes
        </a>
    </li>
    <li role="presentation">
        <a href="#id-of-content-4" role="tab" data-toggle="tab">
            Asignaturas
        </a>
    </li>
</ul>

<!-- INICIO DE LA PESTAÑA CLASES -->
<div class="tab-content ds">
    <div role="tabpanel" id="id-of-content-1" class="tab-pane fade active in">

<a href="<?php echo BASE_URL.'profesor/clases'?>"><button type="submit" class="btn btn-primary">Nueva Clase</button></a>

<!-- TABLA DE LAS CLASES -->
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre de la Clase</th>
      <th scope="col">Asignatura</th>
      <th scope="col">Fecha de Cración</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <?php 
        foreach($this->Get_Clases as $Clases){   
    ?>
      <th scope="row"> <?=$Clases['idclase']?> </th>
      <td> <?=$Clases['tema']?> </td>
      <td> <?=$Clases['asignatura_id_Asignatura']?> </td>
      <td> <?=$Clases['fecha']?> </td>
    </tr>
    <tr>
        <?php }?>
  </tbody>
</table>

<!-- FIN DE LA TABLA -->
</div> 
<!-- /FIN DE LA PESTAÑA CLASES -->

<div role="tabpanel" id="id-of-content-2" class="tab-panel fade ">
        Tab content 2
    </div>
<div role="tabpanel" id="id-of-content-3" class="tab-panel fade ">
        Tab content 3
    </div>

 <div role="tabpanel" id="id-of-content-4" class="tab-pane fade">
   <div class="top-menu">
       <ul class="nav pull-left top-menu">
         <li><a class="logout" data-toggle="modal" href="#" data-target="#NuevaAsignatura">Crear Nueva Asignatura</a></li>
      </ul>
  </div>
 

<!-- TABLA DE LAS Asignatura -->
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre de la Asignatura</th>
      <th scope="col">Creditos</th>
      
    </tr>
  </thead>
  <tbody>
    <tr>
    <?php 
        foreach($this->Get_Asignaturas  as $asignatura){   
    ?>
      <th scope="row"> <?=$asignatura['id_Asignatura']?> </th>
      <td> <?=$asignatura['nombre']?> </td>
      <td> <?=$asignatura['credito']?> </td>
     
    </tr>
    <tr>
        <?php }?>
  </tbody>
</table>
  <?php   include_once ROOT.'views'.DS.'profesor'.DS.'asignaturas.phtml'; ?>
<!-- FIN DE LA TABLA -->
</div> 
<!-- /FIN DE LA PESTAÑA Asignatura-->
   
</div>
  
</div> <!-- fin de col12 --> 
 </div><!-- /row -->
  </section> 
   </section> 