 <!-- ***********************************************************************************************************************************
        Contenido de la vista profesor
 *********************************************************************************************************************************************************** -->
 <!--main content start-->
 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";?> 
  
 <section id="contenido">
    <section class="wrapper">
        <div class="row">
          <div class="col-xs-12 col-md-12 ">        

        
    <ul class="nav nav-tabs nav-justified sidebar-menu" role="tablist">
    <li role="presentation" class="active">
        <a href="#id-of-content-1" role="tab" data-toggle="tab">
            Clases
        </a>
    </li>
    <li role="presentation" >
        <a href="#id-of-content-2" role="tab" data-toggle="tab">
            Asignar Grupos
        </a>
    </li>
    <li role="presentation">
        <a href="#id-of-content-3" role="tab" data-toggle="tab">
            Informes
        </a>
    </li>
    <li role="presentation">
        <a href="#id-of-content-4" role="tab" data-toggle="tab">
            
        </a>
    </li>
</ul>

<!-- INICIO DE LA PESTAÑA CLASES -->
<div class="tab-content ds">
    <div role="tabpanel" id="id-of-content-1" class="tab-pane fade active in">

<a href="<?php echo BASE_URL.'profesor/clases'?>"><button type="submit" class="btn btn-primary">Nueva Clase</button></a>
<br><br><br><br>
<!-- TABLA DE LAS CLASES -->
<table class="table  datatable" id="tb_clases">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre de la Clase</th>
      <th scope="col">Asignatura</th>
      <th scope="col">Fecha de Creación</th>
      <th scope="col">ACCIONES</th>
    </tr>
  </thead>
  <tbody>
    <tr>
    <?php 
        foreach($this->Get_Clases as $Clases){   
    ?>
      <td scope="row"> <?=$Clases['idclase']?> </td>
      <td> <?=$Clases['tema']?> </td>
      <td> <?=$Clases['nombre']?> </td>
      <td> <?=$Clases['fecha']?> </td>
      <td><button class="btn btn-info editBoton" >Editar</button>
      / <button class="btn-borrar btn btn-danger">Borrar</button> </td>
    </tr>
    
        <?php }?>
  </tbody>
</table>
<script type="text/javascript">
  $(document).ready(function(){
    $(".datatable").DataTable();
  })
</script>

<!-- FIN DE LA TABLA -->
</div> 
<!-- /FIN DE LA PESTAÑA CLASES -->

<div role="tabpanel" id="id-of-content-2" class="tab-panel fade ">
        Tab content 2
    </div>
<div role="tabpanel" id="id-of-content-3" class="tab-panel fade ">
        Tab content 3
    </div>

 <div role="tabpanel" id="id-of-content-4" class="tab-pane fade">
  
 


</div> 
<!-- /FIN DE LA PESTAÑA Asignatura-->
   
</div>
  
</div> <!-- fin de col12 --> 
 </div><!-- /row -->
  </section> 
   </section> 