 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";
?> 
 <?php   include_once ROOT.'views'.DS.'student'.DS.'asistencia.phtml'; ?>
           
 
 
   <section id="main-content">
      <section class="wrapper ">
        <div class="row mt">
          <div class="col-lg-9 ">
            <!--CUSTOM CHART START -->
            <div class="style-head" style="font-weight: bold;">
              <h3> Titulo de la clase</h3>
            </div>
            
<!--tabla de asignaturas-->

      <section class="wrapper">
      
        <div class="row mt">
          <div class="col-md-12">
            <div class="content-panel">
          
          
Contenido de la clase:::::::::
 
 
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- /row -->

    
      </section>
  
    <!-- /fin de contenido -->

      
            <!-- /row -->
          </div>
          <!-- /col-lg-9 END SECTION MIDDLE -->
          <!-- **********************************************************************************************************************************************************
               Contenido SIDEBAR Derecho 
              *********************************************************************************************************************************************************** -->
          <div class="col-lg-3 ds">
            <!--panel derecho-->
            <div class="donut-main">
         <h3> Menu </h3>
             <!-- WEATHER PANEL -->
              <div class="col-md-12"><!-- en el css style.css se carga el fondo  -->
              
         
           <ul class="nav pull-cente top-menu">
      
          <li> <a class="logout" href="#" data-toggle="modal" data-target="#myModal" > Marcar Asistencia  </a></li>
            </ul>
           
                <!-- RECENT ACTIVITIES SECTION -->
            <h4 class="centered mt">Documentacion</h4>
            <!-- First Activity -->
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-file"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  Archivos de la clase
                </p>
              </div>
            </div>
            <!-- Second Activity -->
         <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-book"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  Tareas
                </p>
              </div>
            </div>
            <!-- Third Activity -->
          <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-file"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  trabajos de la clase
                </p>
              </div>
            </div>
            <!-- Fourth Activity -->
           <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-file"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  Archivos de la clase
                </p>
              </div>
            </div>

               
          
            
                 </div>
         
           </div>
           
           
          </div>
          <!-- /col-lg-3 -->
        </div>
        <!-- /row -->
      </section>

   
     
    </section>
    <!--main content end-->
   

    