 <section id="main-content">
      <section class="wrapper site-min-height fondo">
      <div class="style-head text-center">  <h3><i class="fa fa-book"></i> Clases</h3></div>
      
        <div class="row mt">
          <div class="col-lg-12 main-chart">
            
                 <!-- Panel muestra las clases -->
              <div class="col-lg-4 col-md-4 col-sm-4 mb">
                <div class="content-panel pn">
                  <div id="profile-01">
                    <h3>Nombre de la clase</h3>
                    <h6>Fecha </h6>
                  </div>
                  <div class="profile-01 centered">
                    <p>Ver Tema</p>
                  </div>
                  <div class="centered">
                    <h6><i class="fa fa-pencil"></i><br/>Nombre de la Asignatura</h6>
                  </div>
                </div>
                <!-- /content-panel -->
              </div>


          </div> 

         </div>   

       </section>     
  </section>         
