 <section id="main-content">
      <section class="wrapper site-min-height fondo">
      <div class="style-head text-center">  <h3><i class="fa fa-book"></i> Clases</h3></div>
      
        <div class="row mt">
          <div class="col-lg-12 main-chart">
          <?php if (isset($this->GetClases) && count($this->GetClases)):?> 
                    <?php for ($i =0; $i < count($this->GetClases);$i++): ?> 
                 <!-- Panel muestra las clases -->
              <div class="col-lg-4 col-md-4 col-sm-4 mb">
                <div class="content-panel pn">
                  <div id="profile-01">
                    <h3> <?php echo $this->GetClases[$i]['tema']?> </h3>
                   
                  </div>
                  <div class="profile-01 centered">
         <a  href="<?php echo BASE_URL . 'student/ClaseDia/'.$this->GetClases[$i]['idclase']?>"><i class="fa fa-edit"></i>      Ver Tema</a>
              
                   <!-- <p>Ver Tema</p>-->
                  </div>
                  <div>
                    <h4 class="centered"><i class="fa fa-calendar"> </i><?php echo $this->GetClases[$i]['fecha']?></h4>
                  </div>
                </div>
                <!-- /content-panel -->
              </div>
      <?php endfor;?> 
         
<?php else: ?>
<h1 class=" titles text-center">No hay Clases Asignadas..........! </h1>

             
<?php endif; ?>    


          </div> 

         </div>   

       </section>     
  </section>         
