 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";
?> 

 <!--pagina de inicio de Estudiante-->
 <section id="main-content">
    <section class="wrapper">
       <div class="row ">

 <div class="col-lg-9 ">        

            <!--Titulo de la tabla -->
            <div class="style-head">
              <h3> Asignaturas Recibidas</h3>
            </div>
       
<!--tabla de asignaturas-->
<?php if (isset($this->GetAsig) && count($this->GetAsig)):?> 
            <!-- tabla que muestra las asignaturas recibidas-->
              <div class="ds">  <!--clase para el fondo blanco -->  
              <table class="table table-striped table-advance table-hover">

                <h4><i class="fa fa-book"></i> Asignaturas</h4>
              <hr>
                <thead>
                  <tr>
                    <th><i class="fa fa-pencil-square-o"></i> Codigo</th>
                    <th class="hidden-phone"><i class="fa fa-list"></i>Nombre de la Asignatura</th>
                    <th><i class="fa fa-calendar"></i> Año Escolar</th>
                    <th><i class="fa fa-bookmark"></i> Creditos</th>
                    
                    <th></th>
                  </tr>
                </thead>
               
                <tbody>
                   
               <?php for ($i =0; $i < count($this->GetAsig);$i++): ?> 

                  <tr>
           <td>  <?php echo $this->GetAsig[$i]['id_Asignatura']?>       </td>
           <td>  <?php echo $this->GetAsig[$i]['nombre']?>        </td>
           <td>  <?php echo $this->GetAsig[$i]['anio_escolar']?>  </td>
           <td>  <?php echo $this->GetAsig[$i]['credito']?>        </td>
                   
            <td>
  <a class="btn btn-success btn-xs" href="<?php echo BASE_URL . 'student/clases/'. $this->GetAsig[$i]['id_Asignatura'];?>"> 
    <i class="fa fa-check"></i> Ver Clases</a>
   <!-- <a class="btn btn-success btn-xs" href="<?php echo BASE_URL . 'student/clases/'?>"><i class="fa fa-check"></i> Ver</a>-->
            </td>
                  </tr>
              
       
      <?php endfor;?>   
         </table>
        </div><!-- /fin de tablas de contenido -->

      
<?php else: ?>
<h1 class=" titles text-center">No hay Asignaturas..........! </h1>

             
<?php endif; ?>    

          
 </div> <!-- /fin clase lg-9 --> 
 
             
           
<!-- Contenido Menu Derecho 
              *********************************************************************************************************************************************************** -->
     <div class="col-lg-3 ds">
            <!--panel derecho-->
            <div class="donut-main">
          
         <h4>Carrera  / año cursado</h4>
         <button id="button1" class="btn btn-success">Opcion 1</button>
             <!-- WEATHER PANEL -->
              <div class="col-md-12"><!-- en el css style.css se carga el fondo  -->
                <div class="weather pn">
                  <i class="fa fa-book fa-4x"></i>
                  <?php foreach ($this->datos_user as $datos_user) { ?>
                  <h3><?=$datos_user['carrera']?> </h3>
                 <?php } ?>
                 <?php foreach ($this->anio_escol as $anio_escol) { ?>
                  <h1>
                    <?=$anio_escol['max(anio_escolar)']?>
                
                   </h1>
                 <?php } ?>
                
               
           </div>
              </div>
                 </div>
         
           
            <!-- Fourth Activity -->
            <div class="desc">
              <div class="thumb">
               <h3>Calendario</h3>
              </div>
            </div>
            
            <!-- CALENDARIO-->
            <div id="calendar" class="mb">
              <div class="panel green-panel no-margin">
                <div class="panel-body">
                  <div id="date-popover" class="popover top" style="cursor: pointer; disadding: block; margin-left: 33%; margin-top: -50px; width: 175px;">
                    <div class="arrow"></div>
                    <h3 class="popover-title" style="disadding: none;"></h3>
                    <div id="date-popover-content" class="popover-content"></div>
                  </div>
                  <div id="my-calendar"></div>
                </div>
              </div>
            </div>
            <!-- / finnal calendario -->
          </div>
          <!-- /col-lg-3 -->
         </div>
        <!-- /row -->
      </section>
      </section>
    <!--main content end-->

           