<!-- **********************************************************************************************************************************************************
       CONTENT de perfil
        *********************************************************************************************************************************************************** -->
    <!--main content start-->

    <section id="main-content">
      <section class="wrapper site-min-height">
        <div class="row mt">

         
          <div class="col-lg-12">
            <div class="row content-panel">
               <div class="container">
              <div class="col-md-4 profile-text mt mb centered">
                <div class="right-divider hidden-sm hidden-xs">
                  <h1>Perfil de usuario</h1>
                  
                </div>
              </div>
              <!-- /col-md-4 -->
              <div class="col-md-4 profile-text ">
                 <br>
                <h3><?php echo Session::get("nombre_estudiante"); ?></h3>
                <h6>Estudiante</h6>
                <?php foreach ($this->datos_user as $datos_user) { ?>

            <i class="fa fa-book">  Carrera</i>
              <h4> <?=$datos_user['carrera']?> </h4>
            
                <br>
               
              </div>
              <!-- /col-md-4 -->
              <div class="col-md-4 centered">
                <div class="profile-pic">
                  <p><img src="<?php echo $_layoutParams['ruta_img'];?>user.png" class="img-circle" ></p>
                  <p>
                    <button data-toggle="modal"  data-target="#Resg_Asistencia" class="btn btn-theme"><i class="fa fa-check"></i> Follow</button>
                    <button class="btn btn-theme02">Add</button>
                  </p>
                </div>
              </div>
              <!-- /col-md-4 -->
            </div>

            </div>
            <!-- /row -->
          </div>
          <!-- /col-lg-12 -->


          <div class="col-lg-12 mt">
            <div class="row content-panel">
              <div class="panel-heading">
                <ul class="nav nav-tabs nav-justified">
                  <li class="active">
                    <a data-toggle="tab" href="#overview">Datos Generales</a>
                  </li>
                  <li>
                    <a data-toggle="tab" href="#contact" class="contact-map">Asignaturas</a>
                  </li>
                  <li>
                    <a data-toggle="tab" href="#edit">Editar Perfil</a>
                  </li>
                </ul>
              </div>
              <!-- /panel-heading -->
              <div class="panel-body">
                <div class="tab-content">
                  <div id="overview" class="tab-pane active">
                    <div class="row">
                      <div class="col-md-12">
                       
                        <div class="grey-style">
                          
                       </div>
                        <div class="detailed mt">
                          <h4>Datos</h4>
                          <div class="recent-activity">
                            <div class="activity-icon bg-theme"><i class="fa fa-pencil"></i></div>
                            <div class="activity-panel">
                            <div class="row contact-info">

<div class="col-md-4">
    <i class="fa fa-credit-card"> Carnet</i>
 <h4> <?=$datos_user['carnet']?>  </h4>
</div>
<br>

<div class="col-md-4">
    <i class="fa fa-users"> Genero</i>
 <h4> <?=$datos_user['sexo']?>  </h4>
</div>
<br>                                
<div class="col-md-4">
    <i class="fa fa-phone"> Telefono</i>
 <h4> <?=$datos_user['telefono']?>  </h4>
</div>
<br>
<div class="col-md-4">
    <i class="fa fa-road"> Departamento</i>
 <h4> <?=$datos_user['departamento']?>  </h4>
</div>
<br>
<div class="col-md-4">
   <i class="fa fa-globe "> Ciudad</i>
   <h4> <?=$datos_user['ciudad']?> </h4>
 </div>
 <br>
<div class="col-md-4">
 <i class="fa fa-envelope"> Email</i>
 <h4> <?=$datos_user['email']?>  </h4>
 </div>
<br>
 <div class="col-md-4">
   <i class="fa fa-lock "> contraseña</i>
   <h4> <?=$datos_user['pass']?>  </h4>
 </div>
 <br>
 <div class="col-md-4">
   <i class="fa fa-calendar "> fecha de Nacimiento</i>
  <h4> <?=$datos_user['FechaNac']?>  </h4>
 </div>
 <br>
 <div class="col-md-4">
   <i class="fa fa-check "> Estado</i>
   <h4> <?=$datos_user['Estado']?>  </h4>
 </div>

 <?php } ?>
</div>
                            </div>
                           
                           
                           
                          </div>
                          <!-- /recent-activity -->
                        </div>
                        <!-- /detailed -->
                      </div>
                      <!-- /col-md-6 -->
                    
                    </div>
                    <!-- /OVERVIEW -->
                  </div>
                  <!-- /tab-pane -->
                  <div id="contact" class="tab-pane">
                    <div class="row">
                     
                      <!-- /col-md-6 -->
                      <div class="col-md-12 detailed">
                        <h4>Asignaturas Recibidas </h4>
                        <div class="col-md-8 col-md-offset-2 mt">
                         
                         <!--tabla de asignaturas-->

      <section class="wrapper">
      
        <div class="row mt">
          <div class="col-md-12">
            <div class="content-panel">
            <?php if (isset($this->asignatura_recib)) {?>
          <!-- tabla que muestra las asignaturas recibidas-->
              <table class="table table-striped table-advance table-hover">
                <h4><i class="fa fa-book"></i> Asignaturas</h4>
                <hr>
                <thead>
                  <tr>
                    <th><i class="fa fa-pencil-square-o"></i> Codigo</th>
                    <th class="hidden-phone"><i class="fa fa-list"></i> Nombre</th>
                    <th><i class="fa fa-bookmark"></i> Credito</th>
                    <th><i class="fa fa-calendar"></i> Año Escolar</th>
                    
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                <?php foreach ($this->asignatura_recib as $asignatura_recib) { ?>

                  <tr>
                    <td>
                      <a href="basic_table.html#"><?=$asignatura_recib['id_Asignatura']?></a>
                    </td>
                    <td class="hidden-phone"><?=$asignatura_recib['nombre']?></td>
                    <td> <?=$asignatura_recib['credito']?></td>
                    <td> <?=$asignatura_recib['anio_escolar']?></td>
                  
                    <td>
                      <button class="btn btn-success btn-xs"><i class="fa fa-check"></i></button>
                      <button class="btn btn-primary btn-xs"><i class="fa fa-pencil"></i></button>
                      <button class="btn btn-danger btn-xs"><i class="fa fa-trash-o "></i></button>
                    </td>
                  </tr>
                  <?php } ?>
                 
          </tbody>
         </table>
         <?php }
 else { 
     ?>

No se han encontrado coincidencias.

<?php } ?>
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- /row -->
      </section>
   
    <!-- /fin de tablas de contenido -->
                        </div>
                        
                      </div>
                      <!-- /col-md-6 -->
                    </div>
                    <!-- /row -->
                  </div>
                  <!-- /tab-pane -->
                  <div id="edit" class="tab-pane">
                    <div class="row">
                      <div class="col-lg-8 col-lg-offset-2 detailed">
                        <h4 class="mb">Informacion Personal</h4>
                        <form role="form" class="form-horizontal">
                          <div class="form-group">
                            <label class="col-lg-2 control-label"> Avatar</label>
                            <div class="col-lg-6">
                              <input type="file" id="exampleInputFile" class="file-pos">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Company</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="c-name" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Lives In</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="lives-in" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Country</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="country" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Description</label>
                            <div class="col-lg-10">
                              <textarea rows="10" cols="30" class="form-control" id="" name=""></textarea>
                            </div>
                          </div>
                        </form>
                      </div>
                      <div class="col-lg-8 col-lg-offset-2 detailed mt">
                        <h4 class="mb">Contact Information</h4>
                        <form role="form" class="form-horizontal">
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Address 1</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="addr1" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Address 2</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="addr2" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Phone</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="phone" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Cell</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="cell" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Email</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="email" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <label class="col-lg-2 control-label">Skype</label>
                            <div class="col-lg-6">
                              <input type="text" placeholder=" " id="skype" class="form-control">
                            </div>
                          </div>
                          <div class="form-group">
                            <div class="col-lg-offset-2 col-lg-10">
                              <button class="btn btn-theme" type="submit">Save</button>
                              <button class="btn btn-theme04" type="button">Cancel</button>
                            </div>
                          </div>
                        </form>
                      </div>
                      <!-- /col-lg-8 -->
                    </div>
                    <!-- /row -->
                  </div>
                  <!-- /tab-pane -->
                </div>
                <!-- /tab-content -->
              </div>
              <!-- /panel-body -->
            </div>
            <!-- /col-lg-12 -->
          </div>
          <!-- /row -->
        </div>
        <!-- /container -->
      </section>
      <!-- /wrapper -->
    </section>
    <!-- /MAIN CONTENT -->
    <!--main content end-->
   