 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";
?> 
 
  <section id="main-content">
      <section class="wrapper ">
     
        <div class="row mt">
          <div class="col-lg-9 ">
             <div class="style-head text-center">
              <h3> Tareas</h3>
            </div>
  <section class="wrapper">
         <div class="row mt">
          <div class="col-md-12">
              <div class="col-lg-4 col-md-4 col-sm-4 mb">
                <div class="content-panel pn">
                  <div id="profile-01">
                    <h3>Nombre de la Tarea</h3>
                    <h6>Fecha </h6>
                  </div>
                  <div class="profile-01 centered">
                    <p>Ver Tarea</p>
                  </div>
                  <div class="centered">
                    <h6><i class="fa fa-pencil"></i><br/></h6>
                  </div>
                </div>
                <!-- /content-panel -->
              </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- /row -->
 
    
      </section>
  
    <!-- /fin de contenido -->

      
        
          </div>
          <!-- /col-lg-9 END SECTION MIDDLE -->
          <!-- **********************************************************************************************************************************************************
               Contenido SIDEBAR Derecho 
              *********************************************************************************************************************************************************** -->
          <div class="col-lg-3 ds">
            <!--panel derecho-->
            <div class="donut-main">
         <h3> Opciones </h3>
             <!-- WEATHER PANEL -->
              <div class="col-md-12"><!-- en el css style.css se carga el fondo  -->
              <form id="asist" name="asist" action="" method="post" autocomplete="off" class="logInForm" >
              <label>Codigo de la clase del dia</label>
           <input required="" class="form-control" id="asistir" name="asistir" type="text" >
             <button type="submit" class="btn btn-success" id="btn_asis">Asistir</button>
             </form> 
       
                <!-- RECENT ACTIVITIES SECTION -->
            <h4 class="centered mt">Documentacion</h4>
            <!-- First opcion -->
            <a  class="logout" href="<?php echo BASE_URL . 'student/Archivos/' ; ?>">
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-archive"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  Archivos 
                </p>
              </div>
            </div>
          </a>
            <!-- Second opcion -->
      <a  class="logout" href="<?php echo BASE_URL . 'student/tarea/' ; ?>">
         <div class="desc">
            <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-book"></i></span>
              </div>
        
              <div class="details">
                 <p>
                  <br/>
                  Tareas
                </p>
              </div>
              </div>
             </a>
            <!-- Third opcion -->
            <a  class="logout" href="<?php echo BASE_URL . 'student/trabajos/' ; ?>">
          <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clipboard"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  trabajos 
                </p>
              </div>
            </div>
          

               
          
            
                 </div>
         
           </div>
           
           
          </div>
          <!-- /col-lg-3 -->
        </div>
        <!-- /row -->
      </section>

   
     
    </section>
    <!--main content end-->
   

    