<section id="main-content">
<div  style="background-color:white " class="container-fluid lead fc-header-title h2" >

   <h2 class="text-center "> <strong> PROPOSICIONES PARA EL CONTROL DE FLUJO DE PROGRAMA </strong></h2>
    <p>&nbsp;</p>
    <ol>
        <li><strong><u> INTRODUCCION</u></strong></li>
    </ol>
    <p>En lo que sigue de este cap&iacute;tulo, denominaremos BLOQUE DE SENTENCIAS al conjunto de sentencias individuales inclu&iacute;das dentro un par de llaves. Por ejemplo :</p>
    <p>{</p>
    <p>sentencia 1 ;</p>
    <p>sentencia 2 ;</p>
    <p>.............</p>
    <p>sentencia n ;</p>
    <p>}</p>
    <p>Este conjunto se comportar&aacute; sintacticamente como una sentencia simple y la llave de cierre del bloque NO debe ir seguida de punto y coma .&nbsp;<br />Un ejemplo de bloque ya visto , es el cuerpo del programa principal de la funci&oacute;n main() .</p>
    <p>main()</p>
    <p>{</p>
    <p>bloque de sentencias</p>
    <p>}</p>
    <p>En las proposiciones de control de flujo de programa , trabajaremos alternativamente con sentencias simples y bloques de ellas .</p>
    <ol start="2">
        <li><strong><u> PROPOSICION IF - ELSE</u></strong></li>
    </ol>
    <p>Esta proposici&oacute;n sirve para ejecutar ciertas sentencias de programa , si una expresi&oacute;n resulta CIERTA &uacute; otro grupo de sentencias, si aquella resulta FALSA. Su interpretaci&oacute;n literal ser&iacute;a : SI es CIERTA tal cosa , haga tal otra , si no lo es salte&eacute;la .</p>
    <p>El caso m&aacute;s sencillo ser&iacute;a :</p>
    <p>if(expresi&oacute;n)</p>
    <p>&nbsp;sentencia ;</p>
    <p>&oacute;</p>
    <p>if(expresi&oacute;n)&nbsp; sentencia ;</p>
    <p>Cuando la sentencia que sigue al IF es &uacute;nica, las dos formas de escritura expresadas arriba son equivalentes . La sentencia s&oacute;lo se ejecutar&aacute; si el resultado de "expresi&oacute;n" es distinto de cero (CIERTO) , en caso contrario el programa saltear&aacute; dicha sentencia ,
     realizando la siguiente en su flujo.&nbsp;<br />&nbsp;Veamos unos ejemplos de las distintas formas que puede 
     adoptar la "expresi&oacute;n" dentro de un IF :&nbsp;<br />&nbsp;&nbsp;&nbsp;</p>           
              

   </div>
   </section>


