 <?php if(isset($_layoutParams['js1']) && count($_layoutParams['js1']))
    for($i=0;$i<count($_layoutParams['js1']);$i++)
        echo "<script src='". $_layoutParams['js1'][$i]."'></script>";
?> 
 
  <section id="main-content">
      <section class="wrapper ">
        <?php foreach ($this->GetClaseDia as $GetClaseDia) { ?> 
        <div class="row mt">
          <div class="col-lg-10 ">
          <!-- <div id="resultado_asistencia"> <?php if(isset($this->_error))echo $this->_error; ?> </div>-->
          
            <!--CUSTOM CHART START -->
            <div class="style-head" style="font-weight: bold;">
       <div class="col-lg-8 "><h4><span>codigo:</span> <span id="id_dia"><?=$GetClaseDia['idclase']?></span> </h4> </div>
          <div class="col-lg-4 "> <h4>Fecha: <?=$GetClaseDia['fecha']?> </h4></div>
           
          <h3 class="text-center">Tema: <?=$GetClaseDia['tema']?> </h3>
         
        </div>
            
  <section class="wrapper">
         <div class="row mt">
          <div class="col-md-12">
            <div class="content-panel">
          
            <strong><h2> CONTENIDO</h2></strong>
        <p class="styletex">
          <br>
         <?=$GetClaseDia['contenido']?>
        </p>
 
 
            </div>
            <!-- /content-panel -->
          </div>
          <!-- /col-md-12 -->
        </div>
        <!-- /row -->
 
    
      </section>
  
    <!-- /fin de contenido -->

      
         <?php } ?>   <!-- /row -->
          </div>
          <!-- /col-lg-9 END SECTION MIDDLE -->
          <!-- **********************************************************************************************************************************************************
               Contenido SIDEBAR Derecho 
              *********************************************************************************************************************************************************** -->
          <div class="col-lg-2 ds">
            <!--panel derecho-->
            <div class="donut-main">
         <h3> Opciones </h3>
             <!-- WEATHER PANEL -->
              <div class="col-md-12"><!-- en el css style.css se carga el fondo  -->
              <label>Maracar Asistencia</label>
              <button type="submit" class="btn btn-success" id="btn_asis">Asistir</button>
           
             <!-- Menu de opciones -->
            <h4 class="centered mt">Documentacion</h4>
            <!-- First opcion -->
            <a  class="logout" href="<?php echo BASE_URL . 'student/Archivos/' ; ?>">
            <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-archive"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  Archivos 
                </p>
              </div>
            </div>
          </a>
            <!-- Second opcion -->
      <a  class="logout" href="<?php echo BASE_URL . 'student/tarea/' ; ?>">
         <div class="desc">
            <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-book"></i></span>
              </div>
        
              <div class="details">
                 <p>
                  <br/>
                  Tareas
                </p>
              </div>
              </div>
             </a>
            <!-- Third opcion -->
            <a  class="logout" href="<?php echo BASE_URL . 'student/trabajos/' ; ?>">
          <div class="desc">
              <div class="thumb">
                <span class="badge bg-theme"><i class="fa fa-clipboard"></i></span>
              </div>
              <div class="details">
                <p>
                 
                  <br/>
                  trabajos 
                </p>
              </div>
            </div>
          

               
          
            
                 </div>
         
           </div>
           
           
          </div>
          <!-- /col-lg-3 -->
        </div>
        <!-- /row -->
      </section>

   
     
    </section>
    <!--main content end-->
   

    